### ISSUE TITLE
Q- How to Cypress test an entire class (check length of elements/number of instances) when using modular CSS

### ISSUE THREAD

**Issue by smithkirsten** [gaybe-safe-haven/gayFE-safe-haven#32]

**Comment by ElBrewster** [comment]
I think we do not need to use the className selector since it is not best practice anyway. Perhaps we can test number of children to the parent div, and use that to check our number of instances of Card.

Reference:
https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

![Image](https://user-images.githubusercontent.com/113723085/229377106-bda523ff-bbf2-4b2a-a067-0458840712de.png)
